<?php
function beecloud_init() {
	drupal_add_css(
		'//res.wx.qq.com/open/libs/weui/0.4.0/weui.min.css',
		array(
			'type' => 'external',
		)
	);
}

function beecloud_menu() {
	$items=array();
	$items['beecloud/offlinepay']=array(
		'title' => 'Charge',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('beecloud_offlinepay_form'),
		'access callback' => TRUE,
	);
	$items['beecloud/webhook']=array(
		'page callback' => 'beecloud_simple_webhook',
		'access callback' => 'beecloud_simple_webhook_perm',
	);
	$items['admin/config/services/beecloud']=array(
		'title' => 'Beecloud settings',
		'description' => 'Beecloud paramenter settings.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('beecloud_settings_form'),
		'access arguments' => array('administer site configuration'),
	);
	
	return $items;
}

function beecloud_offlinepay_form($form, &$form_state) {
	$form['item']=array(
		'#title' => t('Charge item'),
		'#required' => TRUE,
		'#size' => NULL,
		'#maxlength' => 20,
		'#type' => 'textfield',
		'#attributes' => array('class'=>array('weui_input')),
		'#access' => !isset($form_state['storage']['waiting']),
	);

	$form['people']=array(
		'#title' => t('Name'),
		'#required' => TRUE,
		'#size' => NULL,
		'#maxlength' => 20,
		'#type' => 'textfield',
		'#attributes' => array('class'=>array('weui_input')),
		'#access' => !isset($form_state['storage']['waiting']),
	);

	$form['amount']=array(
		'#title' => t('Amount (Yuan)'),
		'#required' => TRUE,
		'#size' => NULL,
		'#maxlength' => 20,
		'#type' => 'textfield',
		'#attributes' => array('class'=>array('weui_input')),
		'#access' => !isset($form_state['storage']['waiting']),
	);
	
	$form['auth_code']=array(
		'#title' => t('Payment Code'),
		'#required' => TRUE,
		'#size' => NULL,
		'#maxlength' => 20,
		'#type' => 'textfield',
		'#attributes' => array('class'=>array('weui_input')),
		'#access' => !isset($form_state['storage']['waiting']),
	);
	
	$form['submit']=array(
		'#value' => t('Charge !'),
		'#required' => TRUE,
		'#type' => 'submit',
		'#attributes' => array('class'=>array('weui_btn weui_btn_primary')),
		'#access' => !isset($form_state['storage']['waiting']),
	);
	
	$form['successmessage']=array(
		'#markup' => sprintf('<div class="weui_msg"><div class="weui_icon_msg weui_icon_success"/><h2 class="weui_msg_title">%s</h2></div>', t('Charge Suceeded')),
		'#access' => $form_state['storage']['waiting']===FALSE,
	);
	$form['ok']=array(
		'#value' => t('OK'),
		'#required' => TRUE,
		'#type' => 'submit',
		'#attributes' => array('class'=>array('weui_btn weui_btn_primary')),
		'#submit' => array('beecloud_offlinepay_form_submit_ok'),
		'#access' => $form_state['storage']['waiting']===FALSE,
	);
	
	$form['query']=array(
		'#value' => t('Query payment status'),
		'#required' => TRUE,
		'#type' => 'submit',
		'#attributes' => array('class'=>array('weui_btn weui_btn_primary')),
		'#submit' => array('beecloud_offlinepay_form_submit_query'),
		'#access' => $form_state['storage']['waiting']===FALSE,
	);

	return $form;
	
}

function beecloud_offlinepay_form_submit($form, &$form_state) {
	$data=array();
	$timestamp=time();

	$data['app_id']=variable_get('beecloud_appid', '');
	$app_secret=variable_get('beecloud_appsecret', '');

	$data['timestamp']=$timestamp;
	$data['app_sign']=md5($data['app_id'].$timestamp.$app_secret);

	if(!isset($form_state['storage']['orderno'])) {
		$data['channel']='WX_SCAN';
		$data['total_fee']=(int)$form_state['values']['amount'];
		$data['bill_no']=date('YmdHis').sprintf('%06d',rand(0,999999));
		$data['title']=t('Charge @name for @item', array('@name'=>$form_state['values']['people'], '@item'=>$form_state['values']['item']));
		$data['auth_code']=$form_state['values']['auth_code'];
		
		$url='https://apidynamic.beecloud.cn/2/rest/offline/bill';
		$options=array(
			'method' => 'POST',
			'headers' => array('Content-Type' => 'application/json'),
			'data' => json_encode($data, JSON_UNESCAPED_UNICODE),
		);
	} else {
		$data['bill_no']=$form_state['storage']['orderno'];
		$data['channel']=$form_state['storage']['channel'];

		$url='https://apidynamic.beecloud.cn/2/rest/offline/bill/status';
		$options=array(
			'method' => 'POST',
			'headers' => array('Content-Type' => 'application/json'),
			'data' => json_encode($data, JSON_UNESCAPED_UNICODE),
		);
	}

	$ret=drupal_http_request(
		$url,
		$options
	);
	
	$result=json_decode($ret->data);

	if($result->resultCode) {
		drupal_set_message($result->err_detail,'error');
	} else {
		if($result->pay_result) {
			$form_state['rebuild']=TRUE;
			$form_state['storage']['waiting']=FALSE;
		} else {
			$form_state['rebuild']=TRUE;
			$form_state['storage']['waiting']=TRUE;
			$form_state['storage']['orderno']=$data['bill_no'];
			$form_state['storage']['channel']=$data['channel'];
		}
	}
}

function beecloud_offlinepay_form_submit_ok($form, $form_state) {
}

function beecloud_settings_form($form, $form_state) {
	$form['beecloud_appid']=array(
		'#type' => 'textfield',
		'#size' => 40,
		'#maxlength' => '36',
		'#title' => 'Beecloud APP ID',
		'#required' => TRUE,
		'#default_value' => variable_get('beecloud_appid', ''),
	);
	$form['beecloud_appsecret']=array(
		'#type' => 'textfield',
		'#size' => 40,
		'#maxlength' => '36',
		'#title' => 'Beecloud APP Secret',
		'#required' => TRUE,
		'#default_value' => variable_get('beecloud_appsecret', ''),
	);
	$form['beecloud_mastersecret']=array(
		'#type' => 'textfield',
		'#size' => 40,
		'#maxlength' => '36',
		'#title' => 'Beecloud Master Secret',
		'#required' => TRUE,
		'#default_value' => variable_get('beecloud_mastersecret', ''),
	);
	return system_settings_form($form);
}

function beecloud_button_js_helper($data, $button_id) {
	drupal_add_js('https://jspay.beecloud.cn/1/pay/jsbutton/returnscripts?appId='.variable_get('beecloud_appid', ''), 'external');

	$data['sign']=md5($data['app_id'] . $data['title'] . $data['amount']. $data['out_trade_no'] . variable_get('beecloud_appsecret', ''));
	drupal_add_js(
		'jQuery(document).ready(function () { '.
			'document.getElementById("'.$button_id.'").onclick = function() {BC.click('.json_encode($data, JSON_UNESCAPED_UNICODE).
		');}'.
		' });',
	'inline');
	
	$order=(object) $data;
	variable_set('order.'.$data['out_trade_no'], $order);
}

function beecloud_simple_webhook_perm() {
	if($_SERVER['REQUEST_METHOD']=='POST') return TRUE;
	else return FALSE;
}

function beecloud_simple_webhook() {
	$jsonStr = file_get_contents("php://input");

	$msg = json_decode($jsonStr);
	
	$sign = md5(variable_get('beecloud_appid', '') . variable_get('beecloud_appsecret', '') . $msg->timestamp);
	if ($sign != $msg->sign ) exit();
	
	if (!$msg->tradeSuccess) exit();
	$order=variable_get('order.'.$msg->transaction_id);
	if ($msg->transaction_fee!=$order->amount) {
		watchdog('beecloud', 'Order %order was hacked by the amount of %amount.', array('%order'=>$msg->transaction_id, '%amount'=>$msg->transaction_fee), WATCHDOG_CRITICAL);
		header('HTTP/1.0 400 Bad Request', 400);
		exit();
	}
	
	switch($msg->transactionType) {
		case 'PAY':
			$order->channel_type=$msg->channel_type;
			variable_set('order.'.$msg->transaction_id, $order);
			watchdog('beecloud', 'Order %order paid successful via %channel.', array('%order'=>$msg->transaction_id, '%channel'=>$msg->channel_type));
			module_invoke_all('beecloud_webhook_paid', $order);
			break;
	}
	echo 'success'; exit;
}

function beecloud_refund_helper($orderno, $amount) {
	$order=variable_get('order.'.$orderno);

	$data=array();
	$timestamp=time();
	$data['app_id']=variable_get('beecloud_appid', '');
	$data['timestamp']=$timestamp;
	$data['app_sign']=md5($data['app_id'].$timestamp.variable_get('beecloud_mastersecret', ''));
	$data['channel']=$order->channel_type;
	$data['refund_no']=date('YmdHis').sprintf('%06d',rand(0,999999));
	$data['bill_no']=$orderno;
	$data['refund_fee']=$order->amount;
	$data['need_approval']=FALSE;
	
	$url='https://apidynamic.beecloud.cn/2/rest/refund';
	$options=array(
		'method' => 'POST',
		'headers' => array('Content-Type' => 'application/json'),
		'data' => json_encode($data, JSON_UNESCAPED_UNICODE),
	);

	$ret=drupal_http_request(
		$url,
		$options
	);
	
	$result=json_decode($ret->data);

	if($result->resultCode) {
		watchdog('beecloud', '%order refund error: %error.', array('%order'=>$orderno, '%error'=>$result->error_detail), WATCHDOG_ERROR);
		drupal_set_message(t('%order refund error: %error.', array('%order'=>$orderno, '%error'=>$result->error_detail)), 'error');
		return FALSE;
	} else {
		if($result->pay_result) {
			return TRUE;
		} else
			return FALSE;
	}
}
?>
